CREATE TABLE IF NOT EXISTS ZAEANNOTATION ( 
    Z_PK INTEGER PRIMARY KEY, 
    Z_ENT INTEGER,                          -- always 1??
    Z_OPT INTEGER,                          -- ??
    ZANNOTATIONDELETED INTEGER,             -- 1 if deleted, 0 if not
    ZANNOTATIONISUNDERLINE INTEGER,         -- ??
    ZANNOTATIONSTYLE INTEGER,               -- int ranging 0 to 3 
    ZANNOTATIONTYPE INTEGER,                -- int ranging 0 to 3
    ZPLABSOLUTEPHYSICALLOCATION INTEGER,    -- always 0 for non-deleted annotations
    ZPLLOCATIONRANGEEND INTEGER,            -- internal annotation range mapping (end)
    ZPLLOCATIONRANGESTART INTEGER,          -- internal annotation range mapping (start)
    ZANNOTATIONCREATIONDATE TIMESTAMP,      -- need to *2500 to get the right date??? 
    ZANNOTATIONMODIFICATIONDATE TIMESTAMP,
    ZANNOTATIONASSETID VARCHAR, 
    ZANNOTATIONCREATORIDENTIFIER VARCHAR, 
    ZANNOTATIONLOCATION VARCHAR,            -- epubCFIs mapping to the correct part of the ebook
    ZANNOTATIONNOTE VARCHAR,                -- note inserted with the highlight
    ZANNOTATIONREPRESENTATIVETEXT VARCHAR,  -- text snippet as representative text
    ZANNOTATIONSELECTEDTEXT VARCHAR,        -- highlighted text
    ZANNOTATIONUUID VARCHAR,                -- unique ID
    ZFUTUREPROOFING1 VARCHAR,               -- ZFUTUREPROOFING columns seem to be reserved for future use
    ZFUTUREPROOFING10 VARCHAR, 
    ZFUTUREPROOFING11 VARCHAR, 
    ZFUTUREPROOFING12 VARCHAR, 
    ZFUTUREPROOFING2 VARCHAR, 
    ZFUTUREPROOFING3 VARCHAR, 
    ZFUTUREPROOFING4 VARCHAR, 
    ZFUTUREPROOFING5 VARCHAR, 
    ZFUTUREPROOFING6 VARCHAR, 
    ZFUTUREPROOFING7 VARCHAR, 
    ZFUTUREPROOFING8 VARCHAR, 
    ZFUTUREPROOFING9 VARCHAR, 
    ZPLSTORAGEUUID VARCHAR,                 -- ??
    ZPLUSERDATA BLOB );                     -- contains something that looks like a plist

CREATE TABLE IF NOT EXISTS ZBCCLOUDSYNCVERSIONS (         -- helps out with sync to the online database
    Z_PK INTEGER PRIMARY KEY, 
    Z_ENT INTEGER, 
    Z_OPT INTEGER, 
    ZCLOUDVERSION INTEGER, 
    ZHISTORYTOKENOFFSET INTEGER, 
    ZLOCALVERSION INTEGER, 
    ZSYNCVERSION INTEGER, 
    ZDATATYPE VARCHAR,
    ZRAWHISTORYTOKEN BLOB );

CREATE TABLE IF NOT EXISTS Z_METADATA (
    Z_VERSION INTEGER PRIMARY KEY, 
    Z_UUID VARCHAR(255), 
    Z_PLIST BLOB);

CREATE TABLE IF NOT EXISTS Z_MODELCACHE (Z_CONTENT BLOB);
CREATE TABLE IF NOT EXISTS Z_PRIMARYKEY (Z_ENT INTEGER PRIMARY KEY, Z_NAME VARCHAR, Z_SUPER INTEGER, Z_MAX INTEGER);

CREATE INDEX IF NOT EXISTS Z_AEAnnotation_annotationAssetID ON ZAEANNOTATION (ZANNOTATIONASSETID COLLATE BINARY ASC);
CREATE INDEX IF NOT EXISTS Z_AEAnnotation_annotationUuid ON ZAEANNOTATION (ZANNOTATIONUUID COLLATE BINARY ASC);